## Initial Preprocessing

In [1]:
# Import dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop unnecessary columns
application_df = application_df.drop(columns=['EIN', 'NAME'], axis=1)

## Optimization Attempt #1
- Reducing Application Type and Classification Bins
- Reduced to 1 Hidden Layer

In [3]:
#Create New DataFrame for Optimization Attempt #1
optim_1_df = application_df.copy()

In [4]:
#Binning Applicaiton Types
application_types_to_replace = ['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17', 'T10']
# Replace in dataframe
for app in application_types_to_replace:
    optim_1_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

In [5]:
#Binning Classifications
classifications_to_replace = list(application_df['CLASSIFICATION'].unique())
classifications_to_keep = ['C1000', 'C2000', 'C1200', 'C3000', 'C2100', 'C7000']
for cls in classifications_to_keep:
    classifications_to_replace.remove(cls)

# Replace in dataframe
for cls in classifications_to_replace:
    optim_1_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

In [6]:
# Get Dummy Columns
categorical_cols = list(optim_1_df.columns)
categorical_cols.remove('ASK_AMT')
processed_df = pd.get_dummies(optim_1_df[categorical_cols])
processed_df['ASK_AMT'] = optim_1_df['ASK_AMT']
processed_df.head()

,STATUS,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,ASK_AMT
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,5000
1,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,108590
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,5000
3,1,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,6692
4,1,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,142590

In [7]:
# Splitting Data
target = processed_df['IS_SUCCESSFUL']
features = processed_df.drop(['IS_SUCCESSFUL'], axis=1)
X_train, X_test, y_train, y_test = train_test_split(features, target)

In [8]:
#Scaling Data
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [9]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=8, activation='relu', input_dim=116))
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6082 - accuracy: 0.7026
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5648 - accuracy: 0.7273
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5575 - accuracy: 0.7275
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5547 - accuracy: 0.7284
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5526 - accuracy: 0.7283
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5515 - accuracy: 0.7298
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5507 - accuracy: 0.7288
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5500 - accuracy: 0.7290
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5494 - accuracy: 0.7304
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5488 - accuracy: 0.7302
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5486 - accuracy: 0.7300
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5483 - accuracy: 0.7301
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7298
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7297
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7301
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7307
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7310
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5467 - accuracy: 0.7309
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7313
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5466 - accuracy: 0.7317
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5466 - accuracy: 0.7308
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5461 - accuracy: 0.7322
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7315
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7308
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7320
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7311
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7315
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7320
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5452 - accuracy: 0.7305
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5452 - accuracy: 0.7331
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5451 - accuracy: 0.7317
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5449 - accuracy: 0.7320
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7333
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7318
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7314
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7322
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7324
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7326
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7318
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5445 - accuracy: 0.7322
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7322
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7322
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7325
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7325
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7324
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7322
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7323
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7318
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5439 - accuracy: 0.7310
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7333
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7326
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7321
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5436 - accuracy: 0.7318
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7328
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7328
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7334
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7319
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7339
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7324
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7331
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7333
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7328
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7329
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7324
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7331
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7325
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7333
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7327
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7337
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7326
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7325
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7329
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7338
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7329
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7320
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7331
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7329
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7325
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7322
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7341
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7330
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7338
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7336
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7338
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7343
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7344
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7324
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7334
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7337
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5426 - accuracy: 0.7322
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7317
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7324
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7336
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7325
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7312
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7336
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5422 - accuracy: 0.7333
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7334
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7334
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7337

In [10]:
# Evaluate the model using the test data
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5732 - accuracy: 0.7338 - 544ms/epoch - 2ms/step
Loss: 0.5731791257858276, Accuracy: 0.7337609529495239

## Optimization Attempt #2
- Increasing Application Type and Classification Bins
- Adding Additonal Hidden Layer

In [11]:
#Create New DataFrame for Optimization Attempt #2
optim_2_df = application_df.copy()

In [12]:
#Binning Applicaiton Types
application_types_to_replace = ['T2', 'T25', 'T14', 'T29', 'T15', 'T17']
# Replace in dataframe
for app in application_types_to_replace:
    optim_2_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

In [13]:
#Binning Classifications
classifications_to_replace = list(application_df['CLASSIFICATION'].unique())
classifications_to_keep = ['C1000', 'C2000', 'C1200', 'C3000', 'C2100', 'C7000', 'C1700', 'C4000']
for cls in classifications_to_keep:
    classifications_to_replace.remove(cls)

# Replace in dataframe
for cls in classifications_to_replace:
    optim_2_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

In [14]:
# Get Dummy Columns
categorical_cols = list(optim_2_df.columns)
categorical_cols.remove('ASK_AMT')
processed_df = pd.get_dummies(optim_2_df[categorical_cols])
processed_df['ASK_AMT'] = optim_2_df['ASK_AMT']
processed_df.head()

,STATUS,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,ASK_AMT
0,1,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,5000
1,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,108590
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,5000
3,1,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,6692
4,1,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,142590

In [15]:
# Splitting Data
target = processed_df['IS_SUCCESSFUL']
features = processed_df.drop(['IS_SUCCESSFUL'], axis=1)
X_train, X_test, y_train, y_test = train_test_split(features, target)

In [16]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=8, activation='relu', input_dim=116))
model.add(tf.keras.layers.Dense(units=6, activation='relu'))
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.7132 - accuracy: 0.5214
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6921 - accuracy: 0.5302
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6906 - accuracy: 0.5317
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6901 - accuracy: 0.5335
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6897 - accuracy: 0.5354
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6897 - accuracy: 0.5348
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6893 - accuracy: 0.5372
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6891 - accuracy: 0.5357
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6889 - accuracy: 0.5382
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6888 - accuracy: 0.5384
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6885 - accuracy: 0.5395
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6886 - accuracy: 0.5388
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6881 - accuracy: 0.5384
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6884 - accuracy: 0.5377
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6882 - accuracy: 0.5393
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6879 - accuracy: 0.5407
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6878 - accuracy: 0.5389
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6880 - accuracy: 0.5391
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6879 - accuracy: 0.5375
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6878 - accuracy: 0.5397
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6876 - accuracy: 0.5404
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6876 - accuracy: 0.5404
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6875 - accuracy: 0.5409
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6874 - accuracy: 0.5426
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6872 - accuracy: 0.5412
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6872 - accuracy: 0.5400
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6871 - accuracy: 0.5411
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6870 - accuracy: 0.5419
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6869 - accuracy: 0.5407
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6869 - accuracy: 0.5406
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6869 - accuracy: 0.5430
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6868 - accuracy: 0.5414
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6867 - accuracy: 0.5408
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6864 - accuracy: 0.5420
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6864 - accuracy: 0.5407
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6864 - accuracy: 0.5425
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6863 - accuracy: 0.5440
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6862 - accuracy: 0.5441
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6862 - accuracy: 0.5424
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6861 - accuracy: 0.5418
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6860 - accuracy: 0.5435
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6859 - accuracy: 0.5433
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6860 - accuracy: 0.5444
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6859 - accuracy: 0.5434
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6859 - accuracy: 0.5422
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6857 - accuracy: 0.5451
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6856 - accuracy: 0.5432
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6856 - accuracy: 0.5438
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6857 - accuracy: 0.5433
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6856 - accuracy: 0.5446
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6854 - accuracy: 0.5452
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6851 - accuracy: 0.5449
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6856 - accuracy: 0.5435
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6854 - accuracy: 0.5442
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6853 - accuracy: 0.5438
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6852 - accuracy: 0.5442
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6852 - accuracy: 0.5450
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6851 - accuracy: 0.5454
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6850 - accuracy: 0.5445
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6849 - accuracy: 0.5455
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6848 - accuracy: 0.5433
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6847 - accuracy: 0.5443
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6848 - accuracy: 0.5444
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6847 - accuracy: 0.5446
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6846 - accuracy: 0.5449
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6848 - accuracy: 0.5467
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6846 - accuracy: 0.5435
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5449
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6844 - accuracy: 0.5445
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6847 - accuracy: 0.5442
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6844 - accuracy: 0.5454
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6845 - accuracy: 0.5459
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6844 - accuracy: 0.5441
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6843 - accuracy: 0.5448
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6843 - accuracy: 0.5453
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6843 - accuracy: 0.5441
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6842 - accuracy: 0.5456
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6841 - accuracy: 0.5464
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6841 - accuracy: 0.5462
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6841 - accuracy: 0.5454
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6842 - accuracy: 0.5436
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6840 - accuracy: 0.5452
Epoch 83/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6840 - accuracy: 0.5435
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6841 - accuracy: 0.5456
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6838 - accuracy: 0.5444
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6843 - accuracy: 0.5444
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6841 - accuracy: 0.5455
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6839 - accuracy: 0.5462
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6840 - accuracy: 0.5434
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6840 - accuracy: 0.5439
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6839 - accuracy: 0.5449
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6837 - accuracy: 0.5439
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6839 - accuracy: 0.5445
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6839 - accuracy: 0.5449
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.6839 - accuracy: 0.5451
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6840 - accuracy: 0.5446
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6836 - accuracy: 0.5449
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6836 - accuracy: 0.5471
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6837 - accuracy: 0.5440
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.6836 - accuracy: 0.5456

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.7068 - accuracy: 0.5296 - 536ms/epoch - 2ms/step
Loss: 0.7067798972129822, Accuracy: 0.5295627117156982

## Optimization Attempt #3
- Using Keras Tuner to find Best Model
- Input Data in same format as Unoptimized Model

In [18]:
#Create New DataFrame for Optimization Attempt #1
optim_3_df = application_df.copy()

In [19]:
#Binning Applicaiton Types
application_types_to_replace = ['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']
# Replace in dataframe
for app in application_types_to_replace:
    optim_3_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

In [20]:
#Binning Classifications
classifications_to_replace = list(application_df['CLASSIFICATION'].unique())
classifications_to_keep = ['C1000', 'C2000', 'C1200', 'C3000', 'C2100']
for cls in classifications_to_keep:
    classifications_to_replace.remove(cls)

# Replace in dataframe
for cls in classifications_to_replace:
    optim_3_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

In [21]:
# Get Dummy Columns
categorical_cols = list(optim_3_df.columns)
categorical_cols.remove('ASK_AMT')
processed_df = pd.get_dummies(optim_3_df[categorical_cols])
processed_df['ASK_AMT'] = optim_3_df['ASK_AMT']
processed_df.head()

,STATUS,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,ASK_AMT
0,1,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,5000
1,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,108590
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,5000
3,1,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,6692
4,1,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,142590

In [22]:
# Splitting Data
target = processed_df['IS_SUCCESSFUL']
features = processed_df.drop(['IS_SUCCESSFUL'], axis=1)
X_train, X_test, y_train, y_test = train_test_split(features, target)

In [23]:
#Scaling Data
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [45]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    model = tf.keras.models.Sequential()
    # Choice of Activation Functions
    activation = hp.Choice('activation', ['relu', 'tanh', 'sigmoid'])
    # Choice of first layer Neurons
    model.add(tf.keras.layers.Dense(units=hp.Int('first_unit',
                                                 min_value=1,
                                                 max_value=10,
                                                 step=2), activation=activation, input_dim=116))
    # Choice of Layers & Layer Neurons
    for i in range(hp.Int('num_layers', 1, 4)):
        model.add(tf.keras.layers.Dense(units=hp.Int('unit_'+str(i),
                                                     min_value=1,
                                                     max_value=10,
                                                     step=2), activation=activation))
    model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
    # Compile the model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [46]:

# Import the kerastuner library
import keras_tuner as kt
# Create a `Hyperband()` tuner instance
tuner = kt.Hyperband(
    create_model,
    objective='val_accuracy',
    max_epochs=50,
    hyperband_iterations=2
)

INFO:tensorflow:Reloading Tuner from .\untitled_project\tuner0.json

In [47]:
#Find top Models
tuner.search(X_train_scaled, y_train, epochs=20, validation_data=(X_test_scaled, y_test))
top_models = tuner.get_best_models(3)

Trial 174 Complete [00h 01m 25s]
val_accuracy: 0.7356268167495728

Best val_accuracy So Far: 0.7381924390792847
Total elapsed time: 00h 53m 32s
INFO:tensorflow:Oracle triggered exit

In [48]:
# Select the top model found
model = top_models[0]

In [52]:
# Evaluate the model using the test data
model_loss, model_accuracy = model.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5449 - accuracy: 0.7319 - 452ms/epoch - 2ms/step
Loss: 0.5448814630508423, Accuracy: 0.7318950295448303

In [53]:
# Export our model to HDF5 file
tf.keras.saving.save_model(
    model, '/Outputs/Model_Optimized/AlphabetSoupCharity_Optimized.h5', save_format='h5'
)

C:\Users\Bryson\AppData\Local\Temp\ipykernel_15696\3441172231.py:2: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  tf.keras.saving.save_model(